### ISSUE TITLE
Rough breakdown of tasks

### ISSUE THREAD

**Issue by seulkilee0428** [kurtiam/Project-Blue-Book#6]
list out the tasks for the current user story and assign them to devs.

**Comment by kurtiam** [comment]
**Kurt** 
1. Flowchart 
2. ticketmaster API  
#api key   IbUXFudvQmR2gZo5kLDiuVkaZTavZiEV)

**Diane**
1. HTML design 
2. CSS

**Seulki**
1. Zomato API 
#api key   328747b9fe3568204c420f6a98d2be68
